export const environment = {
  production: false,
  API_PATH: "<%= API_PATH %>",
  TOPVIEW_API_KEY: "<%= TOPVIEW_API_KEY %>",
  WORKS_API_KEY: "<%= WORKS_API_KEY %>",
  INSTAGRAM_BUSINESS_ACCOUNT: "<%= INSTAGRAM_BUSINESS_ACCOUNT %>",
  INSTAGRAM_ACCESS_TOKEN: "<%= INSTAGRAM_ACCESS_TOKEN %>",
};
